### PR TITLE
added support for sni_host in ddsrouter

### PR DESCRIPTION
**Pull request by amitsingh21**

### CODE REVIEW

**Comment by jparisu** [comment]
This PR requires merge a previous PR in Fast-DDS: https://github.com/eProsima/Fast-DDS/pull/2623

**Review by jparisu — CHANGES_REQUESTED** [review]
@amitsingh21 , thank you very much for your PR.
I've seen you have followed our project format and conventions, thank you very much for that.

I leave here some comments about your PR that should be fixed before merging it. Feel free to apply them or comment in any of them if you are not convinced or have any question.

Also, this PR requires a PR to be merged in `Fast-DDS` beforehand. Thus, this will not be merged for the moment.

**Comment by jparisu** [comment]
CI tests are failing because the CI works against master of Fast-DDS, and it needs a new  feature implemented in PR https://github.com/eProsima/Fast-DDS/pull/2623

**Comment by jparisu** [comment]
This feature will be added within PR #299

**Comment by rsanchez15** [comment]
Closing this PR in favor of #299

**Pull request closed without merging**
